
name: For_Scripts

on:
    push:
        branches: 
            - main
            
jobs:

    welcome:
        runs-on: ubuntu-latest
        steps:
            - name: print Welcome! 
              run: |
                  echo Welcome!
                  
    system_info:
        runs-on: ubuntu-latest
        steps:
            - name: print folder $HOME contents 
              run: |
                  # sudo apt update && sudo apt upgrade 
                  # sudo apt install tree
                  echo in HOME= $HOME :
                  ls -lsai $HOME
            
            - name: print Variables Environement
              run: |
                  printenv
            
            - name: print ~/.bashrc
              run: |
                  cat ~/.bashrc
                  
    
    deploy_repository:
        runs-on : ubuntu-latest
        needs   : welcome
        steps:
            - name: Git_Clone_My_Repository
              run: |
                  uses: actions/checkout@v3
                  
            - name: Setup_Key_on_remote_server
              run: |
                  set -eu
                  mkdir "$HOME/.ssh"
                  echo "{{ secrets.LOCAL_LEGA }}" > "$HOME/.ssh/key"
                  chmod 600 "$HOME/.ssh/key"
